# Generated by Django 5.1.6 on 2025-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profileImage/default_pic.jpg', null=True, upload_to='profileImage/'),
        ),
    ]
